#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export EDITOR="vim"
export VISUAL="vim"

# This stops working for some reason. Commenting out for now.
# Add tmuxinator completion
# source ~/.bin/tmuxinator.zsh

alias mux="tmuxinator"

# Add RVM to Path
#[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unalias rm
# For Ctrl-E etc to work
bindkey -e

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export PATH="$PATH:/Users/ecanaria/scripts"

# TG Aliases
alias tge="mux tg-core"
alias tgs="foreman run rails s -p 3000 -b 0.0.0.0"
alias h-tgconsole="heroku run rails c -rheroku"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
if which rbenv > /dev/null; then eval "$(rbenv init - zsh)"; fi
